{{- if and .Values.ingressDocker.enabled .Values.service.docker.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nexus.fullname" . }}-docker
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
  {{- with .Values.ingressDocker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingressDocker.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- $hosts := .Values.ingressDocker.hosts | default (list .Values.ingressDocker.host) }}
  rules:
    {{- range $host := $hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $.Values.ingressDocker.path }}
            pathType: {{ default "Prefix" $.Values.ingressDocker.pathType }}
            backend:
              service:
                name: {{ include "nexus.fullname" $ }}
                port:
                  number: {{ $.Values.service.docker.port }}
    {{- end }}
  {{- with .Values.ingressDocker.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
