{{- if and .Values.database.enabled .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-db" (include "nexus.fullname" .)) .Values.database.existingSecret }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.usernameKey }}: {{ .Values.database.user | quote }}
  {{ .Values.database.passwordKey }}: {{ required "database.password must be set when database.createSecret is true" .Values.database.password | quote }}
{{- end }}
