apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}-headless
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  {{- if .Values.service.docker.enabled }}
    - name: docker
      port: {{ .Values.service.docker.port }}
      targetPort: docker
      protocol: TCP
  {{- end }}
