apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "nexus.fullname" . }}-headless
  {{- if .Values.ha.podManagementPolicy }}
  podManagementPolicy: {{ .Values.ha.podManagementPolicy }}
  {{- end }}
  {{- with .Values.ha.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nexus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nexus.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nexus.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or (and .Values.persistence.enabled .Values.persistence.chownData) .Values.initContainers }}
      initContainers:
        {{- if and .Values.persistence.enabled .Values.persistence.chownData }}
        - name: nexus-data-permissions
          image: {{ .Values.persistence.chownImage }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chown -R 200:200 /nexus-data && chmod -R g+ws /nexus-data"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
        {{- end }}
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: nexus
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          {{- if .Values.service.docker.enabled }}
            - name: docker
              containerPort: {{ .Values.service.docker.port }}
              protocol: TCP
          {{- end }}
          {{- range .Values.extraPorts }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ default "TCP" .protocol }}
          {{- end }}
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: {{ .Values.javaOpts | quote }}
          {{- if .Values.database.enabled }}
            {{- $secretName := default (printf "%s-db" (include "nexus.fullname" .)) .Values.database.existingSecret }}
            {{- $useSecret := or .Values.database.createSecret .Values.database.existingSecret }}
            - name: NEXUS_DB_USER
              {{- if $useSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.database.usernameKey }}
              {{- else }}
              value: {{ .Values.database.user | quote }}
              {{- end }}
            - name: NEXUS_DB_PASSWORD
              {{- if $useSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .Values.database.passwordKey }}
              {{- else if .Values.database.password }}
              value: {{ .Values.database.password | quote }}
              {{- else }}
              value: ""
              {{- end }}
          {{- end }}
          {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          {{- if or .Values.nexusProperties .Values.database.enabled }}
            - name: nexus-properties
              mountPath: /nexus-data/etc/{{ .Values.nexusPropertiesFilename }}
              subPath: {{ .Values.nexusPropertiesFilename }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- if or (not .Values.persistence.enabled) (or .Values.nexusProperties .Values.database.enabled) (gt (len .Values.extraVolumes) 0) }}
      volumes:
        {{- if not .Values.persistence.enabled }}
        - name: nexus-data
          emptyDir: {}
        {{- end }}
        {{- if or .Values.nexusProperties .Values.database.enabled }}
        - name: nexus-properties
          configMap:
            name: {{ include "nexus.fullname" . }}-nexus-properties
            items:
              - key: {{ .Values.nexusPropertiesFilename }}
                path: {{ .Values.nexusPropertiesFilename }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: nexus-data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        {{- with .Values.persistence.storageClass }}
        storageClassName: {{ . }}
        {{- end }}
  {{- end }}
